// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/common/AppButton.vue')['default']
    Hamburger: typeof import('./src/components/layout/navigation/Hamburger.vue')['default']
    Hero: typeof import('./src/components/hero/Hero.vue')['default']
    Logo: typeof import('./src/components/common/Logo.vue')['default']
    MobileNavigation: typeof import('./src/components/layout/navigation/MobileNavigation.vue')['default']
    Navigation: typeof import('./src/components/layout/navigation/Navigation.vue')['default']
  }
}

export { }
