// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/common/AppButton.vue')['default']
    AppFooter: typeof import('./src/components/layout/footer/AppFooter.vue')['default']
    AppInput: typeof import('./src/components/common/AppInput.vue')['default']
    BackToHome: typeof import('./src/components/auth/BackToHome.vue')['default']
    Collections: typeof import('./src/components/home/Collections.vue')['default']
    ErrorDisplay: typeof import('./src/components/auth/ErrorDisplay.vue')['default']
    Hamburger: typeof import('./src/components/layout/navigation/Hamburger.vue')['default']
    Heart: typeof import('./src/components/misc/Heart.vue')['default']
    Hero: typeof import('./src/components/hero/Hero.vue')['default']
    Logo: typeof import('./src/components/common/Logo.vue')['default']
    MobileNavigation: typeof import('./src/components/layout/navigation/MobileNavigation.vue')['default']
    Navigation: typeof import('./src/components/layout/navigation/Navigation.vue')['default']
    Resource: typeof import('./src/components/shared/Resource.vue')['default']
    Search: typeof import('./src/components/home/Search.vue')['default']
    Spinner: typeof import('./src/components/misc/Spinner.vue')['default']
  }
}

export { }
